const mongoose = require('mongoose')

const schema = mongoose.Schema({
    iso_code: String,
    country: String,
    year: Number,
    co2: Number,
    co2_per_capita: Number,
    trade_co2: Number,
    cement_co2: Number,
    cement_co2_per_capita: Number,
    coal_co2: Number,
    coal_co2_per_capita: Number,
    flaring_co2: Number,
    flaring_co2_per_capita: Number,
    gas_co2: Number,
    gas_co2_per_capita: Number,
    oil_co2: Number,
    oil_co2_per_capita: Number,
    other_industry_co2: Number,
    other_co2_per_capita: Number,
    co2_growth_prct: Number,
    co2_growth_abs: Number,
    co2_per_gdp: Number,
    co2_per_unit_energy: Number,
    consumption_co2: Number,
    consumption_co2_per_capita: Number,
    consumption_co2_per_gdp: Number,
    cumulative_co2: Number,
    cumulative_cement_co2: Number,
    cumulative_coal_co2: Number,
    cumulative_flaring_co2: Number,
    cumulative_gas_co2: Number,
    cumulative_oil_co2: Number,
    cumulative_other_co2: Number,
    trade_co2_share: Number,
    share_global_co2: Number,
    share_global_cement_co2: Number,
    share_global_coal_co2: Number,
    share_global_flaring_co2: Number,
    share_global_gas_co2: Number,
    share_global_oil_co2: Number,
    share_global_other_co2: Number,
    share_global_cumulative_co2: Number,
    share_global_cumulative_cement_co2: Number,
    share_global_cumulative_coal_co2: Number,
    share_global_cumulative_flaring_co2: Number,
    share_global_cumulative_gas_co2: Number,
    share_global_cumulative_oil_co2: Number,
    share_global_cumulative_other_co2: Number,
    total_ghg: Number,
    ghg_per_capita: Number,
    total_ghg_excluding_lucf: Number,
    ghg_excluding_lucf_per_capita: Number,
    methane: Number,
    methane_per_capita: Number,
    nitrous_oxide: Number,
    nitrous_oxide_per_capita: Number,
    population: Number,
    gdp: Number,
    primary_energy_consumption: Number,
    energy_per_capita: Number,
    energy_per_gdp: Number
})

module.exports = mongoose.model('inquinators',schema)



